// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokebooook.Server.Data;

#nullable disable

namespace Pokebooook.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241211042148_UpdateTypes")]
    partial class UpdateTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Pokebooook.Server.Models.Attacks", b =>
                {
                    b.Property<int>("AttackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BaseDamage")
                        .HasColumnType("REAL");

                    b.Property<double>("EnergyCost")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AttackId");

                    b.ToTable("Attacks");
                });

            modelBuilder.Entity("Pokebooook.Server.Models.Locations", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Paths")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PokemonPokedexId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RocketChance")
                        .HasColumnType("REAL");

                    b.HasKey("LocationId");

                    b.HasIndex("PokemonPokedexId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Pokebooook.Server.Models.PokemonTypes", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ToBug")
                        .HasColumnType("REAL");

                    b.Property<double>("ToDark")
                        .HasColumnType("REAL");

                    b.Property<double>("ToDragon")
                        .HasColumnType("REAL");

                    b.Property<double>("ToElectric")
                        .HasColumnType("REAL");

                    b.Property<double>("ToFairy")
                        .HasColumnType("REAL");

                    b.Property<double>("ToFighting")
                        .HasColumnType("REAL");

                    b.Property<double>("ToFire")
                        .HasColumnType("REAL");

                    b.Property<double>("ToFlying")
                        .HasColumnType("REAL");

                    b.Property<double>("ToGhost")
                        .HasColumnType("REAL");

                    b.Property<double>("ToGrass")
                        .HasColumnType("REAL");

                    b.Property<double>("ToGround")
                        .HasColumnType("REAL");

                    b.Property<double>("ToIce")
                        .HasColumnType("REAL");

                    b.Property<double>("ToNormal")
                        .HasColumnType("REAL");

                    b.Property<double>("ToPoison")
                        .HasColumnType("REAL");

                    b.Property<double>("ToPsychic")
                        .HasColumnType("REAL");

                    b.Property<double>("ToRock")
                        .HasColumnType("REAL");

                    b.Property<double>("ToSteel")
                        .HasColumnType("REAL");

                    b.Property<double>("ToWater")
                        .HasColumnType("REAL");

                    b.Property<string>("TypeIcon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TypeId");

                    b.ToTable("PokemonTypes");
                });

            modelBuilder.Entity("Pokebooook.Server.Models.Pokemons", b =>
                {
                    b.Property<int>("PokedexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Attacks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Energy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MainType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PokedexId");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("Pokebooook.Server.Models.Locations", b =>
                {
                    b.HasOne("Pokebooook.Server.Models.Pokemons", "Pokemon")
                        .WithMany()
                        .HasForeignKey("PokemonPokedexId");

                    b.Navigation("Pokemon");
                });
#pragma warning restore 612, 618
        }
    }
}
