name: Nasazení na Sandbox
on:
  release:
    types:
      - released
  workflow_dispatch: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Naklonování repozitáře
        uses: actions/checkout@v4
      
      - name: Seznam souborů
        run: |
          echo "Seznam souborů v kořenovém adresáři:"
          ls -la
          echo "Seznam souborů v adresáři serveru:"
          ls -la Pokebooook.Server || echo "Složka serveru neexistuje"
          echo "Seznam souborů v adresáři data:"
          ls -la data || echo "Složka data neexistuje"
          
      - name: Přihlášení se k Sandboxu
        uses: docker/login-action@v3
        with:
          username: ignored
          password: ${{ secrets.SANDBOX_BUILD_TOKEN }}
          registry: registry.pslib.cloud
          
      - name: Nainstalování Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Sestavení a nahrání kontejnerového obrazu
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.pslib.cloud/sandbox/app-67:latest
